name: object-cache
services:
  bazel-remote:
    container_name: bazel-remote-cache
    command:
      [
        "--max_size=15",
        "--experimental_remote_asset_api",
        "--profile_port=0",
        "--s3.auth_method=access_key",
        "--enable_endpoint_metrics",
      ]
    restart: always
    image: buchgr/bazel-remote-cache:v2.3.3
    user: 0:0
    environment:
      BAZEL_REMOTE_S3_BUCKET: $BAZEL_CACHE_BUCKET
      BAZEL_REMOTE_S3_ENDPOINT: s3.$AWS_REGION.amazonaws.com
      BAZEL_REMOTE_S3_ACCESS_KEY_ID: $AWS_SECRET_ACCESS_KEY
      BAZEL_REMOTE_S3_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      BAZEL_REMOTE_S3_SESSION_TOKEN: $AWS_SESSION_TOKEN
    volumes:
      - ../.cache/bazel/remote:/data:rw
  app:
    image: gcr.io/bazel-public/bazel:7.4.1
    working_dir: /app
    volumes:
      - ../:/app
    depends_on:
      - bazel-remote
